# Generated by Django 4.1.5 on 2023-02-03 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('week_limit', models.PositiveIntegerField()),
                ('is_global', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=280)),
                ('image', models.ImageField(upload_to='images')),
                ('expense', models.DecimalField(decimal_places=2, max_digits=20)),
                ('date_created', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.category')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='available_categories',
            field=models.ManyToManyField(related_name='users', to='tracker.category'),
        ),
    ]
