# Generated by Django 4.1.5 on 2023-02-04 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenditure',
            name='user',
        ),
        migrations.AddField(
            model_name='expenditure',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.category'),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
