# Generated by Django 4.1.5 on 2023-03-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_overall',
            field=models.BooleanField(default=False),
        ),
    ]
