# Generated by Django 4.1.5 on 2023-02-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=280)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('expense', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date_created', models.DateField(auto_now=True)),
            ],
        ),
    ]
