# Generated by Django 4.1.5 on 2023-03-17 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_category_is_binned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='category',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.category'),
        ),
    ]
