# Generated by Django 4.1.5 on 2023-02-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_create_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditure',
            name='is_binned',
            field=models.BooleanField(default=False),
        ),
    ]
