# Generated by Django 4.1.5 on 2023-02-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_expenditure_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
