# Generated by Django 4.1.5 on 2023-02-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_expenditure_is_binned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='description',
            field=models.CharField(max_length=280),
        ),
    ]
