# Generated by Django 4.1.5 on 2023-02-01 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_category_is_global'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
