# Generated by Django 4.1.5 on 2023-02-27 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_expenditure_description'),
        ('tracker', '0004_author_comment_forum_category_reply_post_and_more'),
    ]

    operations = [
    ]
