# Generated by Django 4.1.5 on 2023-02-01 11:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='available_categories',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
