# Generated by Django 4.1.5 on 2023-02-02 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_expenditure_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='description',
            field=models.TextField(max_length=280),
        ),
    ]
