# Generated by Django 4.1.5 on 2023-02-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_expenditure_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='expense',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
