# Generated by Django 4.1.5 on 2023-02-01 12:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_user_available_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='available_categories',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
