# Generated by Django 4.1.5 on 2023-02-06 11:21

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_expenditure_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='expense',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
