# Generated by Django 4.1.5 on 2023-02-03 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_category_user_available_categories'),
        ('tracker', '0006_alter_expenditure_expense'),
    ]

    operations = [
    ]
